spring.application.name=tds_aulas

spring.datasource.url=jdbc:mariadb://localhost:3306/tds_aulas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${MARIADB_SECRET:mariadb}

# JPA
# Hibernate ddl auto (create, create-drop, update, none): com "update" o esquema do database é automaticamente
# modificado, conforme as anotações JPA nas entidades Java da camada de modelo.
spring.jpa.hibernate.ddl-auto=update
# JPA-SQL (as propriedades abaixo instruem o Spring Boot a imprimir o SQL e formatá-lo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
