spring.application.name=tds_aulas

spring.datasource.url=jdbc:mariadb://localhost:3306/tds_aulas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${MARIADB_SECRET:mariadb}

# JPA
# Hibernate ddl auto (create, create-drop, update, none): com "update" o esquema do database é automaticamente
# modificado, conforme as anotações JPA nas entidades Java da camada de modelo.
spring.jpa.hibernate.ddl-auto=update
# JPA-SQL (as propriedades abaixo instruem o Spring Boot a imprimir o SQL e formatá-lo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# adia a inicialização da execução dos scripts para depois da criação dos EntityManager do JPA (o padrão é o script executar antes do JPA)
spring.jpa.defer-datasource-initialization=true
# ordena a execução dos scripts do arquivo data.sql (Valor na primeira execução always. Lembre de colocar para never depois da primeira execução)
spring.sql.init.mode=always
# Configura para ignorar os erros ao tentar repopular as tabelas (já que o spring.sql.init.mode=always está true)
spring.sql.init.continue-on-error=true

# Desabilita a integração do Spring Rest com o Spring Doc
springdoc.enable-data-rest=false